# Generated by Django 6.0.4 on 2026-04-30 09:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', '超级管理员'), ('safety_manager', '安全管理员'), ('inspector', '巡检员'), ('rectifier', '整改负责人')], default='inspector', max_length=20, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'safety_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CampusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='区域名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='区域编码')),
                ('area_type', models.CharField(choices=[('building', '教学楼'), ('dormitory', '宿舍楼'), ('canteen', '食堂'), ('playground', '操场'), ('corridor', '楼道'), ('fire_exit', '消防通道'), ('other', '其他')], max_length=20, verbose_name='区域类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='safety.campusarea', verbose_name='上级区域')),
            ],
            options={
                'verbose_name': '校园区域',
                'verbose_name_plural': '校园区域',
                'db_table': 'campus_area',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InspectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='点位名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='点位编码')),
                ('location', models.CharField(max_length=200, verbose_name='具体位置')),
                ('inspection_frequency', models.CharField(choices=[('daily', '每日'), ('weekly', '每周'), ('monthly', '每月')], default='daily', max_length=20, verbose_name='巡检频次')),
                ('inspection_content', models.TextField(blank=True, verbose_name='巡检内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='safety.campusarea', verbose_name='所属区域')),
                ('responsible_users', models.ManyToManyField(blank=True, related_name='responsible_points', to=settings.AUTH_USER_MODEL, verbose_name='负责巡检人员')),
            ],
            options={
                'verbose_name': '巡检点位',
                'verbose_name_plural': '巡检点位',
                'db_table': 'inspection_point',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='HazardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='隐患标题')),
                ('description', models.TextField(verbose_name='隐患描述')),
                ('hazard_type', models.CharField(choices=[('fire', '消防安全'), ('electric', '用电安全'), ('building', '建筑安全'), ('equipment', '设备安全'), ('food', '食品安全'), ('other', '其他')], max_length=50, verbose_name='隐患类型')),
                ('level', models.CharField(choices=[('general', '一般隐患'), ('serious', '重大安全隐患')], default='general', max_length=20, verbose_name='隐患等级')),
                ('location', models.CharField(max_length=200, verbose_name='具体位置')),
                ('photos', models.JSONField(default=list, verbose_name='隐患照片')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('assigned', '已派单'), ('rectifying', '整改中'), ('completed', '已完成'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='状态')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='整改截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上报时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazards', to='safety.campusarea', verbose_name='所在区域')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_hazards', to=settings.AUTH_USER_MODEL, verbose_name='上报人')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazards', to='safety.inspectionpoint', verbose_name='关联点位')),
            ],
            options={
                'verbose_name': '安全隐患',
                'verbose_name_plural': '安全隐患',
                'db_table': 'hazard_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('normal', '正常'), ('abnormal', '异常')], max_length=20, verbose_name='巡检状态')),
                ('inspection_photos', models.JSONField(default=list, verbose_name='巡检照片')),
                ('remark', models.TextField(blank=True, verbose_name='备注说明')),
                ('inspection_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='巡检时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_records', to=settings.AUTH_USER_MODEL, verbose_name='巡检人')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='safety.inspectionpoint', verbose_name='巡检点位')),
            ],
            options={
                'verbose_name': '巡检记录',
                'verbose_name_plural': '巡检记录',
                'db_table': 'inspection_record',
                'ordering': ['-inspection_time'],
            },
        ),
        migrations.CreateModel(
            name='RectifyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='整改要求')),
                ('deadline', models.DateTimeField(verbose_name='整改截止时间')),
                ('status', models.CharField(choices=[('pending', '待整改'), ('processing', '整改中'), ('submitted', '待验收'), ('completed', '已完成'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='派单时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rectify_tasks', to=settings.AUTH_USER_MODEL, verbose_name='整改负责人')),
                ('assigner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='派单人')),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rectify_tasks', to='safety.hazardreport', verbose_name='关联隐患')),
            ],
            options={
                'verbose_name': '整改任务',
                'verbose_name_plural': '整改任务',
                'db_table': 'rectify_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RectifyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.JSONField(default=list, verbose_name='整改后照片')),
                ('result', models.CharField(blank=True, choices=[('passed', '验收通过'), ('rejected', '验收驳回')], max_length=20, null=True, verbose_name='验收结果')),
                ('remark', models.TextField(blank=True, verbose_name='验收备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='验收时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_records', to=settings.AUTH_USER_MODEL, verbose_name='验收人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='safety.rectifytask', verbose_name='关联整改任务')),
            ],
            options={
                'verbose_name': '整改记录',
                'verbose_name_plural': '整改记录',
                'db_table': 'rectify_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('create', '创建'), ('update', '更新'), ('delete', '删除'), ('export', '导出')], max_length=20, verbose_name='操作类型')),
                ('model_name', models.CharField(max_length=50, verbose_name='操作模型')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='操作对象ID')),
                ('description', models.TextField(blank=True, verbose_name='操作描述')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'db_table': 'system_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
