# Generated by Django 6.0.4 on 2026-05-06 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionrecord',
            name='inspector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_records', to=settings.AUTH_USER_MODEL, verbose_name='巡检人'),
        ),
    ]
