# Generated by Django 6.0.4 on 2026-05-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0002_alter_inspectionrecord_inspector'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardreport',
            name='ai_analysis',
            field=models.TextField(blank=True, verbose_name='AI分析结论'),
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='ai_hazard_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='AI判断隐患类型'),
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='ai_level',
            field=models.CharField(blank=True, max_length=20, verbose_name='AI判断隐患等级'),
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='ai_tags',
            field=models.JSONField(default=list, verbose_name='AI标签'),
        ),
    ]
