# Generated by Django 6.0.4 on 2026-05-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0003_add_hazard_ai_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionrecord',
            name='ai_analysis',
            field=models.TextField(blank=True, verbose_name='AI分析结论'),
        ),
        migrations.AddField(
            model_name='inspectionrecord',
            name='ai_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='AI判断状态'),
        ),
        migrations.AddField(
            model_name='inspectionrecord',
            name='ai_tags',
            field=models.JSONField(default=list, verbose_name='AI标签'),
        ),
    ]
