# Generated by Django 6.0.4 on 2026-05-09 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0004_inspectionrecord_ai_analysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app_enabled', models.JSONField(default=dict, verbose_name='站内通知开关')),
                ('wechat_enabled', models.JSONField(default=dict, verbose_name='微信推送开关')),
                ('wechat_openid', models.CharField(blank=True, default='', max_length=128, verbose_name='微信OpenID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '通知偏好',
                'verbose_name_plural': '通知偏好',
                'db_table': 'notification_preference',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('hazard_new', '新隐患上报'), ('hazard_assigned', '隐患已派单'), ('rectify_submitted', '整改已提交'), ('rectify_approved', '整改已通过'), ('rectify_rejected', '整改已驳回'), ('inspection_overdue', '巡检逾期提醒'), ('ai_abnormal', 'AI异常检测'), ('deadline_approaching', '截止时间临近'), ('deadline_overdue', '整改已逾期')], max_length=30, verbose_name='通知类别')),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('body', models.TextField(verbose_name='通知内容')),
                ('source_type', models.CharField(blank=True, max_length=30, verbose_name='关联类型')),
                ('source_id', models.IntegerField(blank=True, null=True, verbose_name='关联ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('push_sent', models.BooleanField(default=False, verbose_name='已推送')),
                ('push_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='推送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '消息通知',
                'verbose_name_plural': '消息通知',
                'db_table': 'notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a4f9a3_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_201701_idx')],
            },
        ),
    ]
